### ISSUE TITLE
"Давлат назорати инспекцияси" қўшиш

### ISSUE THREAD

**Issue by CCenter-Projects** [ccenter-uz/CRM-UZ-Standart#1]
![image](https://github.com/user-attachments/assets/74d67495-62b7-4392-b8c7-de09279c3f64)

**Comment by Yuldashevmd** [comment]
Tayyor 

![image](https://github.com/user-attachments/assets/497f256f-ca01-4e44-b68d-bde8d92ca240)

**Comment by CCenter-Projects** [comment]
done
