### ISSUE TITLE
Ўзбекчага(кирилл) таржима қилиш

### ISSUE THREAD

**Issue by CCenter-Projects** [ccenter-uz/CRM-UZ-Standart#11]
![image](https://github.com/user-attachments/assets/b6d553ec-b4b1-4fe7-8ee5-d967928d15ff)
![image](https://github.com/user-attachments/assets/41225f32-10ba-48cf-ab55-365b2a933484)
![image](https://github.com/user-attachments/assets/80c31f28-82d6-4b97-9b07-b67fe5552de9)

**Comment by Yuldashevmd** [comment]
Tayyor 

![image](https://github.com/user-attachments/assets/10786566-3a8b-4ffd-b624-69ca99949fb9)
![image](https://github.com/user-attachments/assets/3e3891d2-a206-4fe5-a66e-e95049ea110d)
![image](https://github.com/user-attachments/assets/f8fbee77-096e-4a06-a8d0-623897049c5c)
