### ISSUE TITLE
Ариза юборишда ўзгаришлар

### ISSUE THREAD

**Issue by CCenter-Projects** [ccenter-uz/CRM-UZ-Standart#17]
![Screenshot 2024-08-06 174513](https://github.com/user-attachments/assets/bb151e20-29f5-4336-9c3e-77ac82d8f83f)

1. Рахбарият выборка қўшиш
2. Тегишли идораларга юборилганни олиб ташлаш
3. Мурожаатни жавобини ичидан "тегишли бўйича жўнатилган" ни олиб ташлаб, ўрнига тегишли идорага юборилганни қўшиш

**Comment by Yuldashevmd** [comment]
done
