### ISSUE TITLE
Аризани юклаб олиш

### ISSUE THREAD

**Issue by CCenter-Projects** [ccenter-uz/CRM-UZ-Standart#18]
[Шаблон.docx](https://github.com/user-attachments/files/16510679/default.docx)

1. Инпутлар кетма кетлиги шу шаблон бўйича
2. Юклаб олиш шу шаблон асосида ворд ёки пдф

**Comment by Yuldashevmd** [comment]
Tayyor 

![image](https://github.com/user-attachments/assets/3ee34c5f-4f27-40cb-805c-33b515f0c6c3)
