### ISSUE TITLE
Туманлар хаммасини киритиш зарур

### ISSUE THREAD

**Issue by CCenter-Projects** [ccenter-uz/CRM-UZ-Standart#2]
![image](https://github.com/user-attachments/assets/c332d810-48f9-476f-90fd-cc78dbe9e8b2)

**Comment by Yuldashevmd** [comment]
Tayyor 

![image](https://github.com/user-attachments/assets/b86bd25d-d7bb-4b73-bcf2-a36415df3c38)

**Comment by CCenter-Projects** [comment]
test qilindi, ishladi
