### ISSUE TITLE
Мурожаат ичидаги маълумотларни ажратиш

### ISSUE THREAD

**Issue by CCenter-Projects** [ccenter-uz/CRM-UZ-Standart#20]
![Безымянный](https://github.com/user-attachments/assets/31f318ff-0e72-4371-9f2f-a6a69eade793)

Оператор ва модератор бўйича ажратиш

**Comment by Yuldashevmd** [comment]
Ajraldi 

![image](https://github.com/user-attachments/assets/f5e83c3d-3a8f-4ec3-b644-b032c8521567)
