### ISSUE TITLE
Мурожаат муддатини автоматик белгилаш

### ISSUE THREAD

**Issue by CCenter-Projects** [ccenter-uz/CRM-UZ-Standart#21]
![image](https://github.com/user-attachments/assets/9dae4aa6-8185-46b4-ae2d-14533f21a0e2)

Келиб тушган вақти автоматик белгиланиши керак

**Comment by Yuldashevmd** [comment]
Tayoor 

![image](https://github.com/user-attachments/assets/bbde8f7a-4639-4d4c-878f-3eeb367b8c9b)
