### ISSUE TITLE
Кўриб чиқиш муддатини 15 кун қилиб белгилаш

### ISSUE THREAD

**Issue by CCenter-Projects** [ccenter-uz/CRM-UZ-Standart#22]
Белгиланган кун асосида

1. Мурожаат кўриб чиқиш муддатини қўшиш, автоматик 15 кун бўлади
2. Ариза келиб тушганда автоматик "Кўриб чиқиш жараёнида" статуси белгиланиши (Статусларга алохида селект бўлади)
3. Шу селектни ўзига "Кўриб чиқилган" статустини қўшиш
4. Бу имконият фақат админда бўлади

**Comment by Yuldashevmd** [comment]
Tayyor

![image](https://github.com/user-attachments/assets/f2cf5f12-e4cb-4504-bc24-c9e2c79bb95d)
