### ISSUE TITLE
Dashboard даги карточкаларда ўзгариш

### ISSUE THREAD

**Issue by CCenter-Projects** [ccenter-uz/CRM-UZ-Standart#3]
1 - аризалар
2 - шикоятлар
3 - таклифлар
4 - маълумот бериш

![image](https://github.com/user-attachments/assets/cd44e77b-5ed1-43cf-989c-e3c74643c9f8)

**Comment by Yuldashevmd** [comment]
tayyor 

![image](https://github.com/user-attachments/assets/064ac919-1668-45d2-bac7-2f357ac03b66)

**Comment by CCenter-Projects** [comment]
ishladi, test qilindi
