### ISSUE TITLE
Мурожаат ҳолатига ўзгартириш киритиш

### ISSUE THREAD

**Issue by CCenter-Projects** [ccenter-uz/CRM-UZ-Standart#33]
![image](https://github.com/user-attachments/assets/41fabd58-33c7-45f1-8cd1-1e4e4cd58620)

Мурожаат ҳолатига "Янги" пунктини қўшиш, default ҳолатида шу "Янги" белгиланиши керак.

**Comment by Yuldashevmd** [comment]
done
