### ISSUE TITLE
Йўналишлар бўйича график

### ISSUE THREAD

**Issue by CCenter-Projects** [ccenter-uz/CRM-UZ-Standart#4]
йўналишлар бўйича график:
метрология
сертификатлаштириш
аккредитациялаш
стандартлаштириш
давлат назорати инспекцияси

![image](https://github.com/user-attachments/assets/675881b9-e51d-4f7b-b5cc-0e4b66c04b73)

**Comment by Yuldashevmd** [comment]
tayyor 

![image](https://github.com/user-attachments/assets/9a7d2b38-b677-4c36-a408-d5fc037a3cea)

**Comment by CCenter-Projects** [comment]
ishladi, test qilindi
