### ISSUE TITLE
ҳисобот шакллантириш

### ISSUE THREAD

**Issue by CCenter-Projects** [ccenter-uz/CRM-UZ-Standart#5]
рўйхат бўйича ҳисобот шакллантириш имкониятини қўшиш
шунингдек, тепага (1) сана бўйича фильтр қўйиш

![image](https://github.com/user-attachments/assets/53af990b-a2e5-4963-90fd-5c1c576f4718)

**Comment by Yuldashevmd** [comment]
bu ammalar murojatlar bolimida boladi

**Comment by CCenter-Projects** [comment]
ishladi, test qilindi
