### ISSUE TITLE
-NEW(Feature)-Murojat yaratish jarayonidagi role boyicha dostup

### ISSUE THREAD

**Issue by Yuldashevmd** [ccenter-uz/CRM-UZ-Standart#6]
1) Murojaat yaratish yoki ozgartirishda ijro qilingan sana va murojat javobi qismini operatorlar uchun olib tashlash 
2) Murojaat ni ozgartishda faqatgina admin uchun murojat javobi va ijro qiligan sanani chiqarish 
3) Kiruvchi raqamni olib tashlash 

![image](https://github.com/user-attachments/assets/a89ddd0d-3f98-493c-8f5d-6b5bb1ab930f)

![image](https://github.com/user-attachments/assets/7c77f06a-413e-4208-b8cb-1134d438a388)

**Comment by Yuldashevmd** [comment]
Tayyor 

![image](https://github.com/user-attachments/assets/54fd7ea6-fed5-4bd6-b228-badca9168ae8)

**Comment by CCenter-Projects** [comment]
ishladi, test qilindi
